name: Check

on:
  workflow_call:
    secrets:
      PACKAGES_NPMRC:
        description: 'Token of the Builders Github Packages'
        required: false

jobs:
  check-secret:
      runs-on: ubuntu-latest
      outputs:
        PACKAGES_NPMRC: ${{ steps.PACKAGES_NPMRC.outputs.defined }}
      steps:
          - id: PACKAGES_NPMRC
            env:
                PACKAGES_NPMRC: ${{ secrets.PACKAGES_NPMRC }}
            if: "${{ env.PACKAGES_NPMRC != '' }}"
            run: echo "::set-output name=defined::true"
  check:
    name: Check
    runs-on: ubuntu-latest
    needs: [check-secret]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - if: needs.check-secret.outputs.PACKAGES_NPMRC == 'true'
        name: Set NPM Variables
        run: echo "$PACKAGES_NPMRC" > .npmrc
        env:
          PACKAGES_NPMRC: ${{ secrets.PACKAGES_NPMRC }}
      - name: Install packages
        run: yarn install
      - name: Tests
        run: yarn test
      - name: Linter
        run: yarn lint
